services:
  mongo:
    image: mongo:5.0
    container_name: hylia_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: hylia_backend
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hylia_db
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./docker  
      dockerfile: Dockerfile 
    container_name: hylia_frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always

volumes:
  mongo_data: